# Generated by Django 5.0.6 on 2024-06-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('services', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('namebar', models.CharField(max_length=60)),
                ('services', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('photo', models.CharField(max_length=60)),
            ],
        ),
    ]
